package com.baihui.core.encrypt.gui;

import javax.swing.JOptionPane;

import com.baihui.core.encrypt.util.DecryptClassUtil;
import com.baihui.core.encrypt.util.EncryptClassUtil;

/**
 * ClassName: EncryptFrame
 * @Description: 加密解密客户端
 * @author feifei.liu
 * @date 2016年11月29日 下午3:27:55
 */
@SuppressWarnings("serial")
public class EncryptFrame extends javax.swing.JFrame {
	
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JFileChooser jFileChooser1;
	private javax.swing.JFileChooser jFileChooser2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JTextField jTextField1;

	private String pDir;
	private String sDir;

	/** Creates new form EncryptFrame */
	public EncryptFrame() {
		initComponents();
		setLocationRelativeTo(null);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jFileChooser1 = new javax.swing.JFileChooser();
		jFileChooser2 = new javax.swing.JFileChooser();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();

		this.jFileChooser1.setFileSelectionMode(1);

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("百会CRM加密部署工具");

		jLabel1.setText("选择加密目录");
		
		jLabel2.setText("选择导出目录");

		jTextField1.setEditable(false);

		jButton1.setText("选择");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("加密");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton3.setText("解密");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel1)
								.addComponent(jLabel2)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jTextField1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										198,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jButton1)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jButton2)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jButton3)
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel1)
												.addComponent(jLabel2)
												.addComponent(
														jTextField1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jButton1)
												.addComponent(jButton2)
												.addComponent(jButton3))
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
		// GEN-END:initComponents

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		String path = this.jTextField1.getText();
		if (path == null || path.trim().equals("")) {
			JOptionPane.showMessageDialog(this, "请选择待加密的文件夹！");
		} else {
			this.jButton1.setEnabled(false);
			this.jButton2.setEnabled(false);
			this.jButton3.setEnabled(false);

			JOptionPane.showMessageDialog(this,
					DecryptClassUtil.decrypt(this.sDir, this.pDir));

			this.jButton1.setEnabled(true);
			this.jButton2.setEnabled(true);
			this.jButton3.setEnabled(true);
		}
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		String path = this.jTextField1.getText();
		if (path == null || path.trim().equals("")) {
			JOptionPane.showMessageDialog(this, "请选择待加密的文件夹！");
		} else {
			this.jButton1.setEnabled(false);
			this.jButton2.setEnabled(false);
			this.jButton3.setEnabled(false);

			JOptionPane.showMessageDialog(this,
					EncryptClassUtil.encrypt(this.sDir, this.pDir));

			this.jButton1.setEnabled(true);
			this.jButton2.setEnabled(true);
			this.jButton3.setEnabled(true);
		}
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		this.jFileChooser1.showDialog(this, "选择文件夹");

		this.pDir = this.jFileChooser1.getCurrentDirectory().toString();
		this.sDir = this.jFileChooser1.getSelectedFile().toString();
		this.jTextField1.setText(this.sDir);
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new EncryptFrame().setVisible(true);
			}
		});
	}

}